USE TPI;
CREATE TABLE RESULTADOS(
id INT NOT NULL auto_increment,
RONDA INT,
EQUIPO1 varchar (20),
EQUIPO2 varchar (20),
GOLES1 int,
GOLES2 int,
PRIMARY KEY (ID)
);

CREATE TABLE PRONOSTICOS(
id INT,
PARTICIPANTE varchar (20),
EQUIPO1 varchar (20),
GANA1 varchar (20),
EMPATA varchar (20),
EQUIPO2 varchar (20),
GANA2 varchar (20),
PRIMARY KEY (id)

);
DELETE FROM RESULTADOS WHERE id = 4;
SELECT  * FROM PRONOSTICOS;
INSERT INTO RESULTADOS (RONDA, EQUIPO1, EQUIPO2, GOLES1, GOLES2) VALUES (1,"ARABIA SAUDITA", "MEXICO", 2, 0);
INSERT INTO PRONOSTICOS (ID,PARTICIPANTE,EQUIPO1,GANA1,EMPATA,GANA2,EQUIPO2) VALUES (8,"PEDRO", "ARGENTINA", " ", "X", " ","MEXICO");

